version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "5050:5050"
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5050

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: